USE ADM_SNOWFLAKE;
USE SCHEMA DATAHUB;

ALTER SERVICE DATAHUB_ACTIONS_SVC SUSPEND;
ALTER SERVICE DATAHUB_BROKER_SVC SUSPEND;
ALTER SERVICE DATAHUB_FRONTENDREACT_SVC SUSPEND;
ALTER SERVICE DATAHUB_GMS_SVC SUSPEND;

ALTER SERVICE DATAHUB_ACTIONS_SVC RESUME;
ALTER SERVICE DATAHUB_BROKER_SVC RESUME;
ALTER SERVICE DATAHUB_FRONTENDREACT_SVC RESUME;
ALTER SERVICE DATAHUB_GMS_SVC RESUME;

SHOW SERVICES;

CALL SYSTEM$GET_SERVICE_LOGS('DATAHUB_FRONTENDREACT_SVC', '0','datahub-frontend-react');
CALL SYSTEM$GET_SERVICE_LOGS('DATAHUB_ACTIONS_SVC', '0','datahub-actions');
CALL SYSTEM$GET_SERVICE_LOGS('DATAHUB_BROKER_SVC', '0','broker');
CALL SYSTEM$GET_SERVICE_LOGS('DATAHUB_GMS_SVC', '0','datahub-gms');
