USE ROLE USERADMIN;
CREATE OR REPLACE ROLE DATAHUB_ROLE;

USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS ADM_SNOWFLAKE;
CREATE SCHEMA IF NOT EXISTS ADM_SNOWFLAKE.DATAHUB;
GRANT ROLE DATAHUB_ROLE TO ROLE ACCOUNTADMIN;
GRANT OWNERSHIP ON DATABASE ADM_SNOWFLAKE TO ROLE DATAHUB_ROLE;
GRANT OWNERSHIP ON SCHEMA ADM_SNOWFLAKE.DATAHUB TO ROLE DATAHUB_ROLE;
GRANT OWNERSHIP ON AUTHENTICATION POLICY ADM_SNOWFLAKE.DATAHUB.AUTH_POLICY_DATAHUB_USER TO ROLE DATAHUB_ROLE;

