USE ROLE ACCOUNTADMIN;
CREATE USER DATAHUB_USER
TYPE = SERVICE;
GRANT ROLE DATAHUB_ROLE TO USER DATAHUB_USER;

----------------------------------------------------------------------------------------------------
USE ROLE DATAHUB_ROLE;
CREATE AUTHENTICATION POLICY ADM_SNOWFLAKE.DATAHUB.AUTH_POLICY_DATAHUB_USER
AUTHENTICATION_METHODS = ('OAUTH', 'PROGRAMMATIC_ACCESS_TOKEN');

CREATE NETWORK RULE ADM_SNOWFLAKE.DATAHUB.NET_RULE
TYPE = IPV4
VALUE_LIST = ('0.0.0.0/0');

USE ROLE ACCOUNTADMIN;
CREATE NETWORK POLICY NETWORK_POLICY_DATAHUB_USER
ALLOWED_NETWORK_RULE_LIST = ('ADM_SNOWFLAKE.DATAHUB.NET_RULE');

ALTER USER DATAHUB_USER 
SET NETWORK_POLICY = NETWORK_POLICY_DATAHUB_USER;;

ALTER USER DATAHUB_USER
SET AUTHENTICATION POLICY ADM_SNOWFLAKE.DATAHUB.AUTH_POLICY_DATAHUB_USER;

ALTER USER DATAHUB_USER 
ADD PROGRAMMATIC ACCESS TOKEN TOKEN_01
ROLE_RESTRICTION = 'DATAHUB_ROLE'
DAYS_TO_EXPIRY = 14;
/*
eyJraWQiOiIzNjg5MDExMjAwNSIsImFsZyI6IkVTMjU2In0.eyJwIjoiMTQ0MTAyMTMyOjE0NDEwMjAyMCIsImlzcyI6IlNGOjEwMTYiLCJleHAiOjE3NTA3MjIxNDZ9.ZD2OYLn7sTbovhA-Gi4FveouPAUa16Kh0xqcyFUwgtq90Kyf3DPSO7MM9d2NVy0miCJi_U_MjZMEsQsIqvlnhw
*/

----------------------------------------------------------------------------------------------------
CREATE OR REPLACE NETWORK RULE MANAGE_DB.DATAHUB.DATAHUB_SPCS_EGRESS_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('0.0.0.0:443','0.0.0.0:80');

USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION DATAHUB_SPCS_EGRESS_ACCESS_INTEGRATION
  ALLOWED_NETWORK_RULES = (MANAGE_DB.DATAHUB.DATAHUB_SPCS_EGRESS_RULE)
  ENABLED = TRUE;

GRANT USAGE ON INTEGRATION DATAHUB_SPCS_EGRESS_ACCESS_INTEGRATION TO ROLE DATAHUB_ROLE;
;
