CREATE OR REPLACE WAREHOUSE DATAHUB_WH 
WITH WAREHOUSE_SIZE = 'X-SMALL'
AUTO_SUSPEND = 15;

CREATE COMPUTE POOL DATAHUB_POOL 
COMMENT = '' 
MIN_NODES = 1 
MAX_NODES = 5 
INSTANCE_FAMILY = 'CPU_X64_XS' 
AUTO_RESUME = true 
AUTO_SUSPEND_SECS = 300;

GRANT USAGE ON WAREHOUSE DATAHUB_WH TO ROLE DATAHUB_ROLE;

GRANT READ ON IMAGE       REPOSITORY datahub_repository TO ROLE DATAHUB_ROLE;
GRANT BIND                SERVICE ENDPOINT ON ACCOUNT   TO ROLE DATAHUB_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE         TO ROLE DATAHUB_ROLE;

GRANT MONITOR ON COMPUTE POOL DATAHUB_POOL TO ROLE DATAHUB_ROLE;
GRANT MODIFY  ON COMPUTE POOL DATAHUB_POOL TO ROLE DATAHUB_ROLE;
GRANT OPERATE ON COMPUTE POOL DATAHUB_POOL TO ROLE DATAHUB_ROLE;
GRANT USAGE   ON COMPUTE POOL DATAHUB_POOL TO ROLE DATAHUB_ROLE;
